### ISSUE TITLE
Song playback is very loud

### ISSUE THREAD

**Issue by gus0424** [NotImplementedLife/TaikoSoundEditor#1]
The generated nus3bank files might miss some volume controls attribute which causes the song playback to be very loud.

**Comment by NotImplementedLife** [comment]
Hi! This new version should fix your issue:
https://github.com/NotImplementedLife/TaikoSoundEditor/releases/tag/0.3p2

Also, if you have converted .nus3bank files with the old versions, you can use this program to fix them automatically:
https://github.com/NotImplementedLife/TaikoSoundEditor/releases/tag/template-fix-r
